name: R Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev libfreetype6-dev pkg-config libcurl4-openssl-dev libfontconfig1-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install devtools and package dependencies
        run: |
          Rscript -e 'install.packages("devtools", dependencies = NA)'
          Rscript -e 'install.packages("lintr", dependencies = NA)'
          Rscript -e 'devtools::install_deps(dep = TRUE)'
      
      - name: Check package and tests
        run: |
          Rscript -e 'devtools::check()'
        
      - name: Check linting
        run: |
          Rscript -e "lintr::lint_package(); if (length(lintr::lint_package()) > 0) quit(status = 1)"
