name: R Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("devtools", dependencies = TRUE)'
          Rscript -e 'devtools::install_deps(dep = TRUE)'

      - name: Run R tests
        run: |
          Rscript -e 'devtools::test()'
